# Generated by Django 4.1.7 on 2023-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("image_1", models.ImageField(upload_to="images")),
                ("image_2", models.ImageField(upload_to="images")),
                ("image_3", models.ImageField(upload_to="images")),
                ("address", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=100, null=True)),
                ("text", models.CharField(max_length=500)),
            ],
        ),
    ]
